// Tiny token pipeline: tokens.json -> dist/tokens.css (CSS custom properties in @layer tokens)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const t = JSON.parse(
	readFileSync(new URL('../tokens.json', import.meta.url), 'utf8')
);
const decls = (o) =>
	Object.entries(o)
		.map(([k, v]) => `    --${k}: ${v};`)
		.join('\n');
const brands = Object.keys(t.brands);
const defaultBrand = brands[0];

let css = `/* GENERATED by scripts/build.mjs - do not edit. */\n@layer tokens {\n`;
css += `  :root {\n${decls(t.primitive)}\n${decls(
	t.brands[defaultBrand].base
)}\n${decls(t.themes.light)}\n${decls(
	t.brands[defaultBrand].light
)}\n    color-scheme: light;\n  }\n`;
css += `  [data-theme="dark"] {\n${decls(
	t.themes.dark
)}\n    color-scheme: dark;\n  }\n`;
for (const b of brands) {
	css += `  [data-brand="${b}"] {\n${decls(t.brands[b].base)}\n${decls(
		t.brands[b].light
	)}\n  }\n`;
	css += `  [data-brand="${b}"][data-theme="dark"] {\n${decls(
		t.brands[b].dark
	)}\n  }\n`;
}
css += `}\n`;

mkdirSync(new URL('../dist', import.meta.url), { recursive: true });
writeFileSync(new URL('../dist/tokens.css', import.meta.url), css);
console.log('tokens built:', brands.join(', '));
